language: php

php:
  - 5.4

before_script:
  - composer self-update
  - composer install --prefer-source
  - chmod 0777 tests/_log

script: vendor/bin/codecept run unit

branches:
  only:
    - master